apiVersion: v1
kind: ConfigMap
metadata:
  name: test12-configmap
data:
  appsettings.Production.json: |-
    {
      "ConnectionStrings": {
        "KeyVaultUri": "#{KeyVaultUri}#",
        "ManagedIdentityClientId": "#{ManagedIdentityClientId}#"
      }
    }
